enum STATUS_TYPE {
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED",
    CANCELLED = "CANCELLED",
    DELIVERED = "DELIVERED",
    VERIFIED = "VERIFIED",
    UNVERIFIED = "UNVERIFIED",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    OUT_OF_STOCK = "OUT_OF_STOCK",
    IN_STOCK = "IN_STOCK",
    DRAFT = "DRAFT",
    PUBLISHED = "PUBLISHED",
    UNPUBLISHED = "UNPUBLISHED",
}

enum PAYMENT_STATUS {
    PAID = "PAID",
    UNPAID = "UNPAID",
}

enum ORDER_STATUS {
    PENDING = STATUS_TYPE.PENDING,
    CONFIRMED = STATUS_TYPE.CONFIRMED,
    CANCELLED = STATUS_TYPE.CANCELLED,
    DELIVERED = STATUS_TYPE.DELIVERED,
}

enum ORDER_TYPE {
    PRODUCT = "PRODUCT",
    PACKAGE = "PACKAGE",
}

export {
    STATUS_TYPE,
    PAYMENT_STATUS,
    ORDER_STATUS,
    ORDER_TYPE
}