enum STATUS_TYPE {
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED",
    CANCELLED = "CANCELLED",
    DELIVERED = "DELIVERED",
    VERIFIED = "VERIFIED",
    UNVERIFIED = "UNVERIFIED",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    OUT_OF_STOCK = "OUT_OF_STOCK",
    IN_STOCK = "IN_STOCK",
    DRAFT = "DRAFT",
    PUBLISHED = "PUBLISHED",
    UNPUBLISHED = "UNPUBLISHED",
    PROCESSING = "PROCESSING",
    SHIPPED = "SHIPPED",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED",
    ASSIGNED = "ASSIGNED",
    COMPLETED = "COMPLETED"

}

enum PAYMENT_STATUS {
    PAID = "PAID",
    UNPAID = "UNPAID",
    PENDING = "PENDING",
}

enum ORDER_STATUS {
    PENDING = STATUS_TYPE.PENDING,
    CONFIRMED = STATUS_TYPE.CONFIRMED,
    CANCELLED = STATUS_TYPE.CANCELLED,
    DELIVERED = STATUS_TYPE.DELIVERED,
    ASSIGNED = STATUS_TYPE.ASSIGNED,
    COMPLETED = STATUS_TYPE.COMPLETED
}

enum ORDER_TYPE {
    PRODUCT = "PRODUCT",
    PACKAGE = "PACKAGE",
    KITBAG = "KITBAG",
}

enum PRODUCT_STATUS {
    ACTIVE = STATUS_TYPE.ACTIVE,
    INACTIVE = STATUS_TYPE.INACTIVE,
}

enum USER_TYPE {
    ADMIN = "ADMIN",
    VENDOR = "VENDOR",
    USER = "USER",
    GUEST = "GUEST",
}

export {
    STATUS_TYPE,
    PAYMENT_STATUS,
    ORDER_STATUS,
    ORDER_TYPE,
    USER_TYPE,
    PRODUCT_STATUS
}