import { User } from "@/components/dashboard/users-table";
import { Download, Package, Settings } from "lucide-react";
import { CURRENCY_SYMBOL } from "@/config/app-constant";

export const users: User[] = [
  {
    id: 1,
    name: "Alex Johnson",
    email: "alex@example.com",
    avatar: "https://i.pravatar.cc/40?img=1",
    role: "Admin",
    status: "active",
    joinDate: "2024-01-15",
    location: "New York, US",
  },
  {
    id: 2,
    name: "Sarah Chen",
    email: "sarah@example.com",
    avatar: "https://i.pravatar.cc/40?img=2",
    role: "User",
    status: "active",
    joinDate: "2024-02-20",
    location: "San Francisco, US",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "michael@example.com",
    avatar: "https://i.pravatar.cc/40?img=3",
    role: "Moderator",
    status: "inactive",
    joinDate: "2024-01-08",
    location: "London, UK",
  },
];
export const vendorDashboardCards = [
  {
    title: "Total Vendors",
    value: "1,245",
    change: "+12%",
    changeType: "positive" as const,
    icon: Package,
    color: "text-blue-500",
    bgColor: "bg-blue-100",
  },
  {
    title: "Total Products",
    value: "8,432",
    change: "+8%",
    changeType: "positive" as const,
    icon: Package,
    color: "text-green-500",
    bgColor: "bg-green-100",
  },
  {
    title: "Sales",
    value: `${CURRENCY_SYMBOL} 23,450`,
    change: "-3%",
    changeType: "negative" as const,
    icon: Download,
    color: "text-red-500",
    bgColor: "bg-red-100",
  },
  {
    title: "Active Orders",
    value: "1,120",
    change: "+5%",
    changeType: "positive" as const,
    icon: Settings,
    color: "text-purple-500",
    bgColor: "bg-purple-100",
  },
];
export const adminVendorDashboardCards = [
  {
    title: "Total Vendors",
    value: "1,245",
    change: "+12%",
    changeType: "positive" as const,
    icon: Package,
    color: "text-blue-500",
    bgColor: "bg-blue-100",
  },
  {
    title: "Active Vendors",
    value: "1,120",
    change: "+10%",
    changeType: "positive" as const,
    icon: Settings,
    color: "text-green-500",
    bgColor: "bg-green-100",
  },
  {
    title: "New Vendors",
    value: "125",
    change: "+18%",
    changeType: "positive" as const,
    icon: Package,
    color: "text-purple-500",
    bgColor: "bg-purple-100",
  },
  {
    title: "Vendor Products",
    value: "8,432",
    change: "+8%",
    changeType: "positive" as const,
    icon: Package,
    color: "text-yellow-500",
    bgColor: "bg-yellow-100",
  },
  {
    title: "Sales",
    value: `${CURRENCY_SYMBOL} 32,450`,
    change: "-3%",
    changeType: "negative" as const,
    icon: Download,
    color: "text-red-500",
    bgColor: "bg-red-100",
  },
  {
    title: "Active Orders",
    value: "1,120",
    change: "+5%",
    changeType: "positive" as const,
    icon: Settings,
    color: "text-indigo-500",
    bgColor: "bg-indigo-100",
  },
];
export const adminDashboardData = [
  {
    title: "Monthly Revenue",
    value: `${CURRENCY_SYMBOL} 12,345`,
    change: "+15%",
    changeType: "positive" as const,
    icon: Download,
    color: "text-green-500",
    bgColor: "bg-green-100",
  },
  {
    title: "Total Vendors",
    value: "1,245",
    change: "+12%",
    changeType: "positive" as const,
    icon: Package,
    color: "text-blue-500",
    bgColor: "bg-blue-100",
  },
  {
    title: "Total Payments",
    value: ` ${CURRENCY_SYMBOL} 12,450`,
    change: "+9%",
    changeType: "positive" as const,
    icon: Settings,
    color: "text-purple-500",
    bgColor: "bg-purple-100",
  },
  {
    title: "Total Orders",
    value: "3,452",
    change: "-2%",
    changeType: "negative" as const,
    icon: Package,
    color: "text-red-500",
    bgColor: "bg-red-100",
  },
];
export const notifications = [
  {
    id: 1,
    user: "Chris Tompson",
    action: "requested review on",
    target: "PR #42: Feature implementation",
    timestamp: "15 minutes ago",
    unread: true,
  },
  {
    id: 2,
    user: "Emma Davis",
    action: "shared",
    target: "New component library",
    timestamp: "45 minutes ago",
    unread: true,
  },
  {
    id: 3,
    user: "James Wilson",
    action: "assigned you to",
    target: "API integration task",
    timestamp: "4 hours ago",
    unread: false,
  },
  {
    id: 4,
    user: "Alex Morgan",
    action: "replied to your comment in",
    target: "Authentication flow",
    timestamp: "12 hours ago",
    unread: false,
  },
  {
    id: 5,
    user: "Sarah Chen",
    action: "commented on",
    target: "Dashboard redesign",
    timestamp: "2 days ago",
    unread: false,
  },
  {
    id: 6,
    user: "Miky Derya",
    action: "mentioned you in",
    target: "Origin UI open graph image",
    timestamp: "2 weeks ago",
    unread: false,
  },
];

export const PRODUCT_FORM_DATA: Record<
  string,
  { packageTypes: string[]; units: string[] }
> = {
  Tablet: {
    packageTypes: ["Strip", "Blister", "Bottle", "Box"],
    units: ["tablets"],
  },
  Capsule: {
    packageTypes: ["Strip", "Blister", "Bottle", "Box"],
    units: ["capsules"],
  },
  Syrup: { packageTypes: ["Bottle"], units: ["ml"] },
  Suspension: { packageTypes: ["Bottle"], units: ["ml"] },
  Drops: { packageTypes: ["Bottle"], units: ["ml"] },
  Injection: {
    packageTypes: ["Vial", "Ampoule", "Prefilled Syringe"],
    units: ["ml"],
  },
  Cream: { packageTypes: ["Tube", "Jar"], units: ["g", "ml"] },
  Ointment: { packageTypes: ["Tube", "Jar"], units: ["g"] },
  Gel: { packageTypes: ["Tube", "Pump Bottle"], units: ["g", "ml"] },
  Lotion: { packageTypes: ["Bottle", "Pump Bottle"], units: ["ml"] },
  Powder: { packageTypes: ["Sachet", "Bottle", "Jar", "Box"], units: ["g"] },
  Inhaler: { packageTypes: ["Inhaler Device"], units: ["doses"] },
  Spray: { packageTypes: ["Spray Bottle"], units: ["ml"] },
  Sachet: { packageTypes: ["Sachet", "Box"], units: ["g", "ml"] },
  Patch: { packageTypes: ["Box", "Pouch"], units: ["patches"] },
  Suppository: { packageTypes: ["Box", "Strip"], units: ["units"] },
  "Eye Drops": { packageTypes: ["Bottle"], units: ["ml"] },
  "Ear Drops": { packageTypes: ["Bottle"], units: ["ml"] },
  "Nasal Drops": { packageTypes: ["Bottle"], units: ["ml"] },
  "Effervescent Tablet": { packageTypes: ["Strip", "Box"], units: ["tablets"] },
  Diaper: { packageTypes: ["Pack", "Box"], units: ["pieces"] },
  "Formula Milk": { packageTypes: ["Tin", "Can"], units: ["g", "kg"] },
  Wipes: { packageTypes: ["Pack", "Box"], units: ["pieces"] },
  "Baby Oil": { packageTypes: ["Bottle", "Pump Bottle"], units: ["ml"] },
  "Baby Lotion": { packageTypes: ["Bottle", "Pump Bottle"], units: ["ml"] },
  Liquid: {
    packageTypes: ["Bottle", "Pump Bottle", "Tube"],
    units: ["ml", "oz"],
  },
  Foam: {
    packageTypes: ["Bottle", "Pump Bottle", "Tube"],
    units: ["ml", "oz"],
  },
  Soap: {
    packageTypes: ["Bar"],
    units: ["gram"],
  },
};
